dart_aim_node:
  ros__parameters:
    bound_rate: 115200
    circle_mask: true
    conf_threshold: 0.5
    crop_height: 720
    crop_width: 1280
    h_max: 80
    h_min: 35
    image_topic: /image_raw
    max_area: 130.0
    model_path: ''
    morph_dilate_kernel_size: 5
    morph_kernel_size: 3
    nms_threshold: 0.45
    offset_0_0: 35.0
    offset_0_1: 35.0
    offset_0_2: 35.0
    offset_0_3: 35.0
    offset_1_0: 35.0
    offset_1_1: 35.0
    offset_1_2: 35.0
    offset_1_3: 35.0
    offset_2_0: 12.0
    offset_2_1: 29.0
    offset_2_2: 34.0
    offset_2_3: 30.0
    offset_y: 0.0
    p_err: 8.0
    publish_compressed: true
    publish_compressed_mask: true
    publish_debug_image: true
    s_max: 255
    s_min: 75
    usart_port: /dev/ttyACM0
    use_model: false
    use_serial: true
    v_max: 255
    v_min: 50
